name: Build and Deploy

on:
  push:
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432


    steps:
      - name: Pulling git repo
        uses: actions/checkout@v2

      - name: Instalando o Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.4"

      - name: Update pip
        run: python -m pip install --upgrade pip

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Definir variável DATABASE_URL
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Verificar DATABASE_URL
        run: '[ -z "$DATABASE_URL" ] && echo "DATABASE_URL não está definida" || echo "DATABASE_URL está definida"'
      - name: Esperando o PostgreSQL ficar pronto
        run: sleep 15

      - name: Executar pytest
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
        run: pytest teste.py

